### PR TITLE
Fix footer position

### PR DESCRIPTION
**Pull request by CosmicWebServices**
-Andrew

### CODE REVIEW

**Comment by themightychris** [comment]
@CosmicWebServices could you attach before/after screenshots of what this addresses?

**Comment by CosmicWebServices** [comment]
k

**Comment by CosmicWebServices** [comment]
This keeps the footer on the bottom of the page end makes it so elements cannot go under the footer. This is more of a just in case addition since there is not much position wise on the footer that can cause a site depending on how it is laid out to break.

**Comment by CosmicWebServices** [comment]
I will make a jsfiddle to show what it does

**Comment by CosmicWebServices** [comment]
https://jsfiddle.net/o2kLeLkm/ vs https://jsfiddle.net/o2kLeLkm/1/

**Pull request closed without merging**
