### PR TITLE
Fix blue box issue

### PR DESCRIPTION
**Pull request by CosmicWebServices**
Original issue: https://github.com/SlateFoundation/slate/issues/85

### CODE REVIEW

**Comment by themightychris** [comment]
@CosmicWebServices thanks! could you add another commit to adjust your indentation to be consistent with the rest of the file?

@ryon do you have any suggestions for a better way to write this so we don't have to repeat the properties? Is there a mixin or something that we could use for the box shadow to avoid writing both the standard and the vendor prefixed properties?

**Comment by CosmicWebServices** [comment]
Gotcha

**Comment by CosmicWebServices** [comment]
Fixed

**Comment by themightychris** [comment]
@CosmicWebServices still needs a bit more work, the rest of the file is 4-space indent

**Comment by CosmicWebServices** [comment]
ok

**Comment by themightychris** [comment]
@CosmicWebServices from what I can tell, it looks like this is all that's needed:

```css
.site-branding a:focus {
    box-shadow: none;
}
```

Where there any cases where you found the additional selectors and background-image/outline settings necessary?

It looks like all we need to suppress is the box-shadow set here: https://github.com/JarvusInnovations/emergence-skeleton-v2/blob/master/site-root/sass/skeleton/modules/_forms.scss#L131

@ryon take a look at that `:focus` selector in forms.scss... seems a little aggressive no? Shouldn't we scope that down to inputs?

**Comment by CosmicWebServices** [comment]
For cross compatibility the extra things are needed

**Comment by ryon** [comment]
@themightychris You can focus elements other than inputs (links, buttons, anything with a tabindex applied). For accessibility, focused elements deserve some kind of visual indication.

As to the original issue, perhaps we could move some styles around to make the box encompass the entire logo instead of intersecting it? Or give it some kind of custom focus treatment? I'm reluctant to wipe out focus styling just because it's a little ugly.

**Comment by themightychris** [comment]
@ryon if it should be universal lets move it to common.scss instead of being in forms.scss

I wasn't able to see any focus styling on text links and buttons

**Comment by themightychris** [comment]
@ryon re the original issue, making the a box accurately encompass the image within it seems like a good step. Is that something we cold do universally or best just handled for the header logo case?

**Comment by CosmicWebServices** [comment]
Should I put this into _common.scss to fix your concerns

**Pull request closed without merging**
